
version: "3.9"

name: utlectives

services:
  db:
    image: postgres
    container_name: my-postgres-container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - utlectives-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    image: my-docker-image
    container_name: my-docker-container
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8001:8000"
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
    networks:
      - utlectives-network

networks:
  utlectives-network: