# Generated by Django 4.2.4 on 2025-06-04 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='availability',
            field=models.JSONField(default=list),
        ),
    ]
