# Generated by Django 4.2.4 on 2025-06-04 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_reviews', '0002_course_availability'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='availability',
            new_name='sessions',
        ),
    ]
