# Generated by Django 4.2.4 on 2025-06-09 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_reviews', '0004_alter_course_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='page_reference',
            field=models.URLField(blank=True, null=True),
        ),
    ]
