# Generated by Django 4.2.4 on 2025-06-16 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_reviews', '0006_review_is_anonymous'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='course_completion',
            field=models.CharField(help_text='Format: YYYY-Season (e.g., 2025-Autumn)', max_length=20),
        ),
    ]
