# Generated by Django 4.2.4 on 2025-06-19 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_reviews', '0007_alter_review_course_completion'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='faculty',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
