# Generated by Django 5.2.1 on 2025-08-16 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_reviews', '0009_alter_review_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['-review_count', '-overall_rating', 'code']},
        ),
        migrations.AddField(
            model_name='course',
            name='review_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
