# Generated by Django 5.2.1 on 2025-09-01 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_reviews', '0010_alter_course_options_course_review_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['-overall_rating', '-review_count']},
        ),
        migrations.AddField(
            model_name='course',
            name='has_sessions',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
