# Generated by Django 5.2.1 on 2025-09-13 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_reviews', '0011_alter_course_options_course_has_sessions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['-has_sessions', '-overall_rating', '-review_count']},
        ),
        migrations.AddField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('UG', 'Undergraduate'), ('PG', 'Postgraduate')], db_index=True, default='UG', max_length=2),
        ),
    ]
