name: Publish Docker Images

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: |
          python -m pip install --upgrade pip
          pip install -r dev-requirements.txt
      - run: playwright install chromium --with-deps
      - run: pytest

  publish-docker:
    name: Publish Docker Images
    runs-on: ubuntu-latest
    needs: test
    permissions: 
      packages: write
      id-token: write
    env:
      IMAGE: ghcr.io/progsoc/utlectives
      REGISTRY: ghcr.io
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE }}:latest
          platforms: linux/amd64,linux/arm64

  deploy:
    needs: publish-docker
    runs-on: ubuntu-latest
    steps:
      - uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /opt/progsoc/utlectives
            docker pull ghcr.io/progsoc/utlectives:latest
            docker compose down
            docker compose up -d
            docker image prune -f
