name: Publish Docker Images

on:
  push

jobs:
  
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r dev-requirements.txt
      
      - name: Install Playwright browsers
        run: |
          playwright install chromium --with-deps

      - name: Run tests
        run: |
          pytest


  build_and_publish:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - name: Build and push Docker Image
        run: |
          docker login ghcr.io --username charmandercodes --password ${{ secrets.UTLECTIVES_PAT }}
          docker build . -t ghcr.io/progsoc/utlectives
          docker push ghcr.io/progsoc/utlectives
  deploy:
    needs: build_and_publish
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    
    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            # Navigate to your project directory
            cd /opt/progsoc/utlectives
            
            # Pull the latest image
            docker pull ghcr.io/progsoc/utlectives
            
            # Stop and remove existing containers
            docker compose down
            
            # Start containers with new image
            docker compose up -d
            
            # Optional: Clean up old images
            docker image prune -f

           
